# Generated by Django 6.0 on 2026-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_registrationrequest_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='temporary_password',
            field=models.CharField(blank=True, help_text='Admin: Set this before approving.', max_length=128),
        ),
    ]
