# Generated by Django 6.0 on 2026-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_registrationrequest_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Check this and click SAVE to create the account.'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='student_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='temporary_password',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
