# Generated by Django 6.0 on 2026-01-29 06:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_alter_profile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMasterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="ID must start with 'S' followed by 6 digits (e.g., S000001).", regex='^S\\d{6}$')])),
                ('full_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=100)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('REJECTED', 'Rejected'), ('PAYMENT_REQUIRED', 'Awaiting Payment'), ('PAID', 'Paid - To be Processed'), ('PROCESSING', 'Processing Document'), ('READY', 'Ready for Pickup'), ('COMPLETED', 'Claimed/Finished')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
