# Generated by Django 6.0 on 2026-02-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_otptoken_studentmasterlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_record', to='requests_app.studentmasterlist')),
            ],
        ),
    ]
