# Generated by Django 6.0 on 2026-02-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='generated_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
