# Generated by Django 6.0 on 2026-02-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_documentrequest_generated_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='receipt', max_length=50)),
                ('last_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
