# Generated by Django 6.0 on 2026-02-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0011_collectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='printed_name',
            field=models.CharField(blank=True, help_text='Name as it appears on receipts', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_text',
            field=models.CharField(blank=True, help_text='Stylized signature text', max_length=255),
        ),
    ]
