# Generated by Django 6.0 on 2026-02-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0012_profile_printed_name_profile_signature_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signature_text',
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='printed_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
