# Generated by Django 6.0 on 2026-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0013_remove_profile_signature_text_profile_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
