# Generated by Django 6.0 on 2026-02-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0014_documentrequest_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='generated_content',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='delivery_method',
            field=models.CharField(choices=[('PICKUP', 'In-person Pickup'), ('LBC', 'LBC Delivery')], default='PICKUP', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('REJECTED', 'Rejected'), ('PAYMENT_REQUIRED', 'Awaiting Payment'), ('PAID', 'Paid - To be Processed'), ('PROCESSING', 'Processing Document'), ('READY', 'Ready for Pickup / Shipping'), ('COMPLETED', 'Claimed/Finished')], default='PENDING', max_length=20),
        ),
    ]
