# Generated by Django 6.0 on 2026-02-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0015_remove_documentrequest_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='generated_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
