# Generated by Django 6.0 on 2026-02-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0016_documentrequest_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
