# Generated by Django 6.0 on 2026-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0018_documentrequest_shipping_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='lbc_branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='lbc_type',
            field=models.CharField(blank=True, choices=[('RIDER', 'Rider Delivery (Home)'), ('BRANCH', 'Branch Pick Up')], default='RIDER', max_length=10, null=True),
        ),
    ]
