# Generated by Django 6.0 on 2026-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0019_documentrequest_lbc_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlog',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash (Manual)'), ('ONLINE', 'Xendit (Online)')], default='CASH', max_length=10),
        ),
    ]
