# Generated by Django 6.0 on 2026-02-25 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0022_chatbotfaq_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('student', 'office')},
        ),
    ]
