# Generated by Django 6.0 on 2026-02-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0023_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
