# Generated by Django 6.0 on 2026-02-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0024_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotFAQ',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
