# Generated by Django 4.2.29 on 2026-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0025_delete_chatbotfaq_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='google_auth_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otptoken',
            name='google_auth_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
