# Generated by Django 4.2.29 on 2026-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0026_otptoken_google_auth_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='tor_page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages for TOR (Transcript of Records)', null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='tor_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom price for TOR based on page count', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentmasterlist',
            name='is_graduated',
            field=models.BooleanField(default=False, help_text='Whether the student has graduated'),
        ),
    ]
