# Generated by Django 4.2.29 on 2026-03-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0027_documentrequest_tor_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='rush_processing',
            field=models.BooleanField(default=False, help_text='If true, processing is rushed (1 day) at double price'),
        ),
    ]
