# Generated by Django 4.2.29 on 2026-03-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0028_documentrequest_rush_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='processing_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days to process the document', null=True),
        ),
    ]
