# Generated by Django 4.2.29 on 2026-03-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0029_documentrequest_processing_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('PENDING_TOR_COUNT', 'Pending TOR Page Count'), ('APPROVED', 'Approved - Awaiting Payment'), ('REJECTED', 'Rejected'), ('PAYMENT_REQUIRED', 'Awaiting Payment'), ('PAID', 'Paid - To be Processed'), ('PROCESSING', 'Processing Document'), ('READY', 'Ready for Pickup / Shipping'), ('COMPLETED', 'Claimed/Finished')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TORRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=False, help_text='Whether this was a free TOR request')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_history', to='requests_app.studentmasterlist')),
            ],
            options={
                'verbose_name': 'TOR Request History',
                'verbose_name_plural': 'TOR Request Histories',
                'ordering': ['-requested_at'],
            },
        ),
    ]
